# Relative path(s) to your source files
source: ./src/scss

# Relative path where you want the documentation to be built
destination: styleguide

# The path that contains supporting assets for the documentation page
documentation_assets: bower_components/hologram-github-theme

# Category that will be used as the index.html (optional)
index: styleguide

# A list of relative paths to folders containing any dependencies to copy ie. assets, icons
dependencies:
  - './dist/fonts'
  - './dist/css'

# The CSS file links to be included in the styleguide
css_include:
  - 'css/rise.min.css'
  - 'css/alignment.min.css'

# The JavaScript files to included in the styleguide
js_include:
  # - 'dist/js/common-header.min.js'

# The global title that is displayed at the top of the pages
global_title: Rise Vision Style Guide